databases:
  - name: agrimind-db
    databaseName: agrimind
    user: agrimind_user

services:
  # Web Service (Django + React)
  - type: web
    name: agrimind-app
    runtime: python
    buildCommand: npm run deploy:fullstack:render
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.4"
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: NODE_VERSION
        value: "18"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: VITE_GEMINI_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: DATABASE_URL
        fromDatabase:
          name: agrimind-db
          property: connectionString
